# Check for variable prefix
# Problem, I need a way to define multiple projects
# Options:
#  - Configuration by some kind of manifest file that can be read by the pipeline?
#  - Prefixing env variables
#  - 
job:
  image: artifactory.cloud.cms.gov/docker/alpine:latest
  script:
    - echo "Building application named ${APP_NAME} using dockerfile ${TARGET_DOCKERFILE}"
  parallel:
    matrix:
      - APP_NAME: "app-one"
        TARGET_DOCKERFILE: "Dockerfile.app-one"
      - APP_NAME: "app-two"
        TARGET_DOCKERFILE: "Dockerfile.app-two"
