variables:
  TEMPLATE_VERSION: "feat/mono-repo-support"

sast-pipeline:
  needs: []
  variables:
    SCAN_GITLEAKS: "true"
    SCAN_SEMGREP: "true"
  trigger:
    strategy: depend
    include:
      - project: "devops-pipelines/pipeline-triggers"
        ref: ${TEMPLATE_VERSION}
        file: "sast.yaml"
  parallel:
    matrix:
      - APP_NAME: "frontend"
        TARGET_DIRECTORY: "frontend"
        SEMGREP_RULES_ADD: "p/javascript" 
        ARTIFACT_FOLDER: ".artifacts/frontend"
        APP_IMAGE_SRC: ${BC_IMAGE_REPO}/${CI_PROJECT_PATH}/frontend
      - APP_NAME: "counter-api"
        TARGET_DIRECTORY: "counter-api"
        SEMGREP_RULES_ADD: "p/golang" 
        ARTIFACT_FOLDER: ".artifacts/counter-api"
        APP_IMAGE_SRC: ${BC_IMAGE_REPO}/${CI_PROJECT_PATH}/counter-api
