version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - COUNTER_API="http://localhost:3020"
        - CHAT_API="ws://localhost:3030"
    ports:
      - "8081:8080"
    depends_on:
      - counter-api
    volumes:
      - $PWD/frontend/src/:/var/www/kl/ 
    networks:
      - mono-network

  counter-api:
    build:
      context: ./counter-api
      dockerfile: Dockerfile
    command: "/app/counter-api --addr :3020"
    networks:
      - mono-network
    ports:
      - "3020:3020"

  chat-api:
    build:
      context: ./chat-api
      dockerfile: Dockerfile
    command: "/app/chat-api --addr :3030"
    networks:
      - mono-network
    ports:
      - "3030:3030"

networks:
  mono-network:
