version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - COUNTER_API="http://localhost:3020"
        - CHAT_API="ws://localhost:3030"
    ports:
      - "8081:80"
    depends_on:
      - counter-api
    volumes:
      - $PWD/frontend/src/:/var/www/kl/ 
    networks:
      - mono-network

  counter-api:
    build: ./counter-api
    depends_on:
      - redis-server
    environment:
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
    networks:
      - mono-network
    ports:
      - "3020:3000"

  chat-api:
    build: ./chat-api
    networks:
      - mono-network
    environment:
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
    depends_on:
      - redis-server
    ports:
      - "3030:3000"

  redis-server:
    image: redis:alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '6379:6379'
    volumes:
      - kl-mono:/data
    networks:
      - mono-network


networks:
  mono-network:

volumes:
  kl-mono:
    driver: local
